import type { Kysely } from "kysely";
import type { Database } from "./types.ts";

export interface StudentSubscriptions {
  courses: Array<{ designation: string; title: string | null }>;
  sections: Array<{
    designation: string;
    section_id: string;
    status: string;
    available_seats: number;
  }>;
}

/**
 * Maps a better-auth user id (an access token's `sub`) to that user's email.
 *
 * Subscriptions are keyed by email while tokens carry a user id, so every
 * read goes through here. The email is never accepted as input and never
 * cached across requests — serving one student's email for another's token
 * is precisely the failure this indirection must not produce.
 *
 * `"user"` is cast because better-auth owns that table (schema/002_better_auth.sql,
 * generated by the better-auth CLI) and it has no entry in the generated
 * `Database` type in `pg/types.ts` — there is nothing to type against.
 */
export async function resolveUserEmail(
  db: Kysely<Database>,
  userId: string
): Promise<string | null> {
  const row = await db
    .selectFrom("user" as any)
    .select(["email"])
    .where("id", "=", userId)
    .executeTakeFirst();
  return (row as { email?: string } | undefined)?.email ?? null;
}

/** Everything one student is watching. Read-only by construction. */
export async function findSubscriptions(
  db: Kysely<Database>,
  email: string
): Promise<StudentSubscriptions> {
  const courses = await db
    .selectFrom("course_subscriptions")
    .innerJoin("courses", "courses.id", "course_subscriptions.course_id")
    .select(["courses.course_designation as designation", "courses.course_title as title"])
    .where("course_subscriptions.email", "=", email)
    .orderBy("courses.course_designation")
    .execute();

  const sections = await db
    .selectFrom("section_subscriptions")
    .innerJoin("sections", "sections.id", "section_subscriptions.section_id")
    .innerJoin("courses", "courses.id", "sections.course_ref")
    .select([
      "courses.course_designation as designation",
      "sections.section_id as section_id",
      "sections.status as status",
      "sections.available_seats as available_seats",
    ])
    .where("section_subscriptions.email", "=", email)
    .orderBy("courses.course_designation")
    .execute();

  return { courses, sections };
}
